
robot_model: bumi1            # 机型: bumi1 / bumi2
clean_actuator_error: true   # 启动时是否清除电机错误

imu:
  source: "ethercat"          # IMU数据来源类型: "usb" 或 "ethercat"
  usb_port: "/dev/ttyACM0"    # USB串口端口 (仅当source为usb时有效)
  ethercat_canu: "body"       # EtherCAT CANU名称 (仅当source为ethercat时有效)
hw_log:
  LogLevel: 4      #  0:trace, 1:debug, 2:info, 3:warn, 4:err, 5:critical, 6:off
  LogType:  "100"  # Consol, Rotate, Udp
  RotateLog: 
    Count: 5
    FileName: "hw_module"
    OpenNew:  "true"
    PathName: "."
    Size(MB): 20
  UdpLog:
    HostName: "Noetix"
    IP: "127.0.0.1"
    Port: 514

ethercat:
  ifname:  enp2s0       
  bind_cpu: 9            
  rt_priority: 90        
  enable_dc: true         
  cycle_time_ns: 1000000  

actuator_list:
  - name: l_arm_pitch_joint
    direction: 1                          
    bias: 0
  - name: l_arm_roll_joint
    direction: 1                          
    bias: 0
  - name: l_arm_yaw_joint
    direction: -1                          
    bias: 0
  - name: l_elbow_pitch_joint
    direction: 1                          
    bias: 0
  - name: l_leg_pitch_joint
    direction: 1                        
    bias: 0
  - name: l_leg_roll_joint
    direction: 1                          
    bias: 0
  - name: l_leg_yaw_joint
    direction: -1                          
    bias: 0
  - name: l_knee_pitch_joint
    direction: 1                         
    bias: 0
  - name: l_ankle_pitch_joint
    direction: 1                          
    bias: 0
  - name: l_ankle_roll_joint
    direction: -1                          
    bias: 0
  - name: r_arm_pitch_joint
    direction: -1                          
    bias: 0
  - name: r_arm_roll_joint
    direction: 1                          
    bias: 0
  - name: r_arm_yaw_joint
    direction: -1                          
    bias: 0
  - name: r_elbow_pitch_joint
    direction: -1                          
    bias: 0
  - name: r_leg_pitch_joint
    direction: -1                          
    bias: 0
  - name: r_leg_roll_joint
    direction: 1                          
    bias: 0
  - name: r_leg_yaw_joint
    direction: -1                          
    bias: 0
  - name: r_knee_pitch_joint
    direction: -1                          
    bias: 0
  - name: r_ankle_pitch_joint
    direction: -1                          
    bias: 0
  - name: r_ankle_roll_joint
    direction: 1                          
    bias: 0
  - name: waist_yaw_joint
    direction: 1  
    bias: 0

canu_network:             # CANU通信网络，请根据实机连接情况配置
  - name: body            # CANU索引名字
    ecat_id: 1            # CANU在EtherCAT网络中的ID，从主站开始，第一个从站ID为1，依次增加
    enable: true          # 使能该CANU
    imu_enable: true      # 使能该CANU的IMU
    channel_1:            # CANU的CTRL-1通道配置
      - name: waist_yaw_joint          
        type: ACTR_F5014                
        can_id: 1                       
    channel_2:            
      - name: l_arm_pitch_joint
        type: ACTR_4308                 
        can_id: 1                           
      - name: l_arm_roll_joint
        type: ACTR_4308                  
        can_id: 2                             
      - name: l_arm_yaw_joint
        type: ACTR_4308                   
        can_id: 3                            
      - name: l_elbow_pitch_joint
        type: ACTR_4308                   
        can_id: 4 
    channel_3:            
      - name: l_leg_pitch_joint
        type: ACTR_F5014                  
        can_id: 1                             
      - name: l_leg_roll_joint
        type: ACTR_F5014                 
        can_id: 2                             
      - name: l_leg_yaw_joint
        type: ACTR_4308                  
        can_id: 3                             
      - name: l_knee_pitch_joint
        type: ACTR_F5014                 
        can_id: 4                             
      - name: l_ankle_pitch_joint
        type: ACTR_4308                 
        can_id: 5                            
      - name: l_ankle_roll_joint
        type: ACTR_4308                   
        can_id: 6 
  - name: hip             
    ecat_id: 2             
    enable: true                  
    channel_2:            
      - name: r_arm_pitch_joint
        type: ACTR_4308                  
        can_id: 1                           
      - name: r_arm_roll_joint
        type: ACTR_4308                  
        can_id: 2                             
      - name: r_arm_yaw_joint
        type: ACTR_4308                   
        can_id: 3                            
      - name: r_elbow_pitch_joint
        type: ACTR_4308                   
        can_id: 4                            
    channel_3:            
      - name: r_leg_pitch_joint
        type: ACTR_F5014                  
        can_id: 1                             
      - name: r_leg_roll_joint
        type: ACTR_F5014                  
        can_id: 2                             
      - name: r_leg_yaw_joint
        type: ACTR_4308                  
        can_id: 3                             
      - name: r_knee_pitch_joint
        type: ACTR_F5014                 
        can_id: 4                             
      - name: r_ankle_pitch_joint
        type: ACTR_4308                 
        can_id: 5                            
      - name: r_ankle_roll_joint
        type: ACTR_4308                  
        can_id: 6                    

